# Site settings
title: Liranhu's Blog
SEOTitle: 胡理燃的博客 | Happy everday
header-img: img/myfig_ocean_index.jpg
email: codeliranhu@gmail.com
description: "以梦为马，不负韶华"
keyword: "liranhu"
url: "http://codeliranhu.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/codeliranhu/codeliranhu.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "以梦为马，不负韶华!"
sidebar-avatar: /img/myprofile-1.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:      codeliranhu
#zhihu_username:     qiubaiying
instagram_username:    lrhu_jason
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
#gitalk:
  #enable: false    #是否开启Gitalk评论
  #clientID: f2c84e7629bb1446c1a4                            #生成的clientID
  #clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
  #repo: codeliranhu.github.io    #仓库名称
 # owner: codeliranhu    #github用户名
  #admin: codeliranhu
 # distractionFreeMode: true #是否启用类似FB的阴影遮罩



<!-- Gitalk 评论 start  -->
{% if site.gitalk.enable %}
<!-- Link Gitalk 的支持文件  -->
<link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
<script src="https://unpkg.com/gitalk@latest/dist/gitalk.min.js"></script>

<div id="gitalk-container"></div>
    <script type="text/javascript">
    var gitalk = new Gitalk({

    // gitalk的主要参数
        clientID: `117d7e8353618ef5cc61`,
        clientSecret: `0efdd2a2c096d7a54b706e0660000d56e46ca171`,
        repo: `codeliranhu.github.io`,
        owner: 'codeliranhu',
        admin: 'codeliranhu',
        id: 'window.location.pathname',
    
    });
    gitalk.render('gitalk-container');
</script>
{% endif %}
<!-- Gitalk end -->


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "instagram",
        href: "https://www.instagram.com/lrhu_jason/?hl=zh-cn"
    },{
        title: "weibo",
        href: "https://weibo.com/7416968639/profile?rightmod=1&wvr=6&mod=personinfo&is_all=1"
    }
    #,{
       # title: "Apple",
     #   href: "https://apple.com"
   # },{
       # title: "Apple Developer",
     #  href: "https://developer.apple.com/"
    #}#
]
